spring.application.name=BookStore

spring.datasource.url=jdbc:mysql://switchyard.proxy.rlwy.net:51807/pubs
spring.datasource.username=root
spring.datasource.password=ctsNsaDaPUBWWAWsPkbGhEpLkqxiADkr
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.data.rest.base-path=/api
server.port=8085

